steps:
  # Build MLflow
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mlflow-server', '-f', 'Dockerfile.mlflow', '.']
  
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '-f', 'Dockerfile.backend', '.']
  
  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', '-f', 'Dockerfile.frontend', '.']

# Push all images
images:
  - 'gcr.io/$PROJECT_ID/mlflow-server'
  - 'gcr.io/$PROJECT_ID/backend'
  - 'gcr.io/$PROJECT_ID/frontend'

