FROM python:3.11.13

# Copy src dest
COPY backend/ /app

WORKDIR /app

# install all python packages
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]

