# IMPORTANT: we use cloudbuild.yaml which built by GCP directly, not built locally as it will only be arm instead amd
services:
  mlflow:
    build:
      context: .                                # use dockerfile in current dir
      dockerfile: Dockerfile.mlflow             # dockerfile name
    image: gcr.io/mldatamanage/mlflow-server    # tag name
    ports:
      - "5000:5000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: gcr.io/mldatamanage/backend
    ports:
      - "8000:8000"
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: gcr.io/mldatamanage/frontend
    ports:
      - "3000:3000"
