FROM python:3.11.13

# Install python packages
RUN pip install mlflow[extras] google-cloud-storage

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:///data/mlflow.db", \
     "--default-artifact-root", "gs://neuralripper-mlflow-artifacts/artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000"]