steps:
  # Build MLflow
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mlflow-server', '-f', 'Dockerfile.mlflow', '.']

images:
  - 'gcr.io/$PROJECT_ID/mlflow-server'