services:
  mlflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mlflow
    ports: ["5000:5000"]
    restart: unless-stopped
    volumes: [mlflow_data:/var/lib/mlflow/mlflow-db]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-west-2

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports: ["8000:8000"]
    restart: unless-stopped
    environment:
      - MLFLOW_TRACKING_URI=https://neuralripper.com/mlflow  # Use production mlflow for both local dev and actual training
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-west-2

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        VITE_API_BASE_URL: https://neuralripper.com/api
    ports: ["3000:3000"]
    restart: unless-stopped

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
    ports: ["80:80", "443:443"]
    restart: unless-stopped
    depends_on: [frontend, backend, mlflow]

volumes:
  mlflow_data:
