services:
  mlflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mlflow
      platforms: [linux/amd64]
    # ECR: name of the image: registry/repo_name:tag
    image: 970547374353.dkr.ecr.us-east-1.amazonaws.com/neuralripper:mlflow

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
      platforms: [linux/amd64]
    # ECR: name of the image: registry/repo_name:tag
    image: 970547374353.dkr.ecr.us-east-1.amazonaws.com/neuralripper:backend
  
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      platforms: [linux/amd64]
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    # ECR: name of the image: registry/repo_name:tag
    image: 970547374353.dkr.ecr.us-east-1.amazonaws.com/neuralripper:frontend

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
      platforms: [linux/amd64]
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    # ECR: name of the image: registry/repo_name:tag
    image: 970547374353.dkr.ecr.us-east-1.amazonaws.com/neuralripper:nginx