FROM python:3.11.13

# Install mlflow and aws s3 lib
RUN pip install mlflow>=2.8.0 boto3

RUN mkdir -p /var/lib/mlflow/mlflow-db

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////var/lib/mlflow/mlflow-db/mlflow.db", \
     "--default-artifact-root", "s3://neuralripper/mlflow-artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000"]