services:
  mlflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mlflow
      platforms: [linux/amd64]
    image: 970547374353.dkr.ecr.us-west-2.amazonaws.com/neuralripper:mlflow   # Pull from ECR

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
      platforms: [linux/amd64]
    image: 970547374353.dkr.ecr.us-west-2.amazonaws.com/neuralripper:backend  # Pull from ECR
  
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      platforms: [linux/amd64]
    image: 970547374353.dkr.ecr.us-west-2.amazonaws.com/neuralripper:frontend  # Pull from ECR